### ISSUE TITLE
Add properly configured .gitignore file

### ISSUE THREAD

**Issue by JohnKhandygo** [angdust/BitSet#1]
В .gitignore файле описываются файлы и директории, которые необходимо исключить при работе с данным репоиторием в git. В число таких файлов, как правило, включают специфичные для пользователей файлы, что позволяет избежать конфликтов при конкурентной работе с репозиторием. В частности, сюда целесообразно отнести файлы, [генерируемые IDE](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems), поскольку их формат и содержание может отличаться от версии к версии. Для генерации .gitignore в idea удобно использовать [.ignore плагин](https://plugins.jetbrains.com/plugin/7495--ignore).

**Comment by angdust** [comment]
Добавил

**Comment by JohnKhandygo** [comment]
Некоторые игнорируемые файлы все еще отслеживаются (tracks) git'ом. То есть любые изменения в таких файлах как и раньше могут быть запушены в удаленные репозиторий. Для того, чтобы избавиться от ненужных файлов окончательно, используйте команду [git-clean](https://git-scm.com/docs/git-clean).

**Comment by angdust** [comment]
А где можно ознакомиться с использованием команд, не могу найти? (куда вводить и прочее)

**Comment by JohnKhandygo** [comment]
https://proglib.io/p/git-for-half-an-hour/

**Comment by angdust** [comment]
Добавил изменения

**Comment by JohnKhandygo** [comment]
Здесь мой косяк, не так git команда. Правильную инструкцию смотри [здесь](https://gist.github.com/scy/6636390).

**Comment by angdust** [comment]
Исправил, использовав команду "git clean -i -X". Вроде понял, что такое .gitignore и с чем его едят.

**Comment by JohnKhandygo** [comment]
Не похоже, что это сработало, поскольку лишние файлы все еще в удаленном репозитории. Если поняли, то окей.
