### ISSUE TITLE
Use consistent code style/formatting

### ISSUE THREAD

**Issue by JohnKhandygo** [angdust/BitSet#3]
В исходном коде программы встречаются разночтения стиля кодирования/форматирования. В качестве референсного стиля кодирования можно использовать [google java style guide](https://google.github.io/styleguide/javaguide.html).

**Comment by angdust** [comment]
Исправил

**Comment by JohnKhandygo** [comment]
Актуально.

**Comment by angdust** [comment]
Исправил (не хватало переносов с использование фигурных скобок)
