### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by JohnKhandygo** [angdust/BitSet#4]
По условиям первого задания весь разработанный код должен быть покрыт тестами. Для вычисления процента покрытия используйте [Run with Coverage](https://www.jetbrains.com/help/idea/running-with-coverage.html). От Вас, естественно, не требуется покрывать тестами такие методы, как `equals`, `hashCode` и `toString`.

**Comment by angdust** [comment]
Сделано

**Comment by JohnKhandygo** [comment]
Не все сценарии использования покрыты тестами. 

После выполнения действия Run with Coverage можно открыть файл класса, который тестировался (в Вашем случае `BitSet`) и [посмотреть](https://www.jetbrains.com/help/idea/viewing-code-coverage-results.html), какие блоки кода остались не покрытыми.

**Comment by angdust** [comment]
Частично добавил по недостающим строкам, но остался еще метод "Union", который прост так не дает.

**Comment by JohnKhandygo** [comment]
У Вас в `union` не покрыта ветка `else`, в нее передается управление, когда размер множества `other` больше, чем размер базового (`this`) множества. Значит надо просто добавить тест, в котором выполняется это условие.

**Comment by angdust** [comment]
Все добавил
