### ISSUE TITLE
Reimplement BitSet

### ISSUE THREAD

**Issue by JohnKhandygo** [angdust/BitSet#6]
Вы, видимо, неправильно поняли условие задачи. В рамках данного проекта Вам необходимо разработать упрощенный [стандартный java bit set](https://docs.oracle.com/javase/7/docs/api/java/util/BitSet.html).

**Comment by angdust** [comment]
Исправил

**Comment by JohnKhandygo** [comment]
Вы просто заменили `List` на `Vector`. Учитывая, что `Vector` --- это synchronized аналог `ArrayList`, такое "исправление" ничего не меняет.

**Comment by angdust** [comment]
Но Ведля я также исправил методы и теперь я работаю только с битами

**Comment by JohnKhandygo** [comment]
С чего Вы взяли, что работаете с битами? Несмотря на то, что логически тип `boolean` кодирует один бит информации, это не значит, что он занимает ровно столько места в памяти программы (привет, Java!). В  java размер, который занимает `boolean` зависит от реализации JVM, которую Вы используете ([официальная документация](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html), [статейка на хабре](https://habrahabr.ru/post/76481/)). Кроме того, Вы оперируете не примитивным `boolean`, а `Boolean` (boxed boolean), который является классом. Boxed типы всегда занимают больше памяти, поскольку для класса также хранится заголовок, таблица виртуальных методов и прочее. В масштабах бита это очень много.

**Comment by angdust** [comment]
Все еще не могу разобраться с условием....Просто, то что вы сказали про BitSet и то, что есть в условии совсем разное. Можно тогда чуть больше объяснить условие, пожалуйста?

**Comment by angdust** [comment]
Исходник стандартного BitSeta не помог, а усугубил понимание

**Comment by JohnKhandygo** [comment]
Условие:
Реализовать множество над заданным набором объектов. Количество элементов в наборе задается в конструкторе. Конкретный элемент набора идентифицируется неотрицательным целым от нуля до количества элементов - 1 (альтернатива -- уникальным именем).

Операции: пересечение, объединение, дополнение; добавление/удаление заданного элемента (массива элементов), проверка принадлежности элемента множеству.

Бонус: итератор по множеству.

Покажите, в чем конкретно расхождение с тем, что я Вам рассказывал. Попробуем разобраться.

Строго говоря, если Вы понимаете, что такое логические операции и как предоставляются числа в двоичной системе счисления (обычные беззнаковые целые числа), то никаких проблем быть не должно.

**Comment by JohnKhandygo** [comment]
Если Вы уберите Boolean и замените его на что-то, что будет хранить признак наличия элемента в множестве, используя один бит, то все будет окей. Должно получиться ровно то, что надо.

**Comment by angdust** [comment]
Заменил на ArrayList с интами.

**Comment by JohnKhandygo** [comment]
Каждый `int` занимает 32 бита (а `Integer` и того больше, но пока забудем про это). Таким образом, Вы используете 32 бита для того, чтобы закодировать присутствие/отсутствие одного объекта, а должны использовать **1 бит**. Эта реализация по факту ничем не отличается от предыдущей (если я правильно помню, то нечто подобное у Вас было еще в первой версии).  

Прочитайте, как представляются целые положительные числа в двоичной системе счисления. Именно таким образом любой `int` или `long` хранится в памяти. Используя простейшие [битовые операции](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/op3.html), Вы можете вычислить значение любого бита в `int`'е. Таким образом, можно хранить один `int` для кодирования состояния 32ух объектов. Это именно то, что Вам надо сделать. И именно так работает стандартный [`BitSet`](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/util/BitSet.java), просто там куча дополнительной логики для того, чтобы размер выделяемой памяти увеличивался с добавлением новых объектов. Вам ничего подобного делать, конечно, не надо, просто фиксированный размер.

**Comment by JohnKhandygo** [comment]
Альтернативный вариант: закрываете остальные комментарии, получаете следующее задание и минимальную положительную оценку за это. Только напишите о своем решении явно.

**Comment by angdust** [comment]
Выбираю, первый вариант(с минимальной оценкой)

**Comment by JohnKhandygo** [comment]
Окей, закрывайте остальные замечания. Второе задание постараюсь выслать сегодня в течение дня.

**Comment by angdust** [comment]
Добавил изменения по другим замечаниям. Жду условие второго задания.
