### ISSUE TITLE
Use common project structure

### ISSUE THREAD

**Issue by JohnKhandygo** [angdust/BitSet#7]
В java принято орагнизовывать классы в пакеты. Общепринятые правила именования пакетов см. [здесь](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). Понятно, что у Вас скорее всего нет никакого сайта. В этом случае можно его придумать или взять название орагнизации, в рамках которой делается проект. Например, `org.spbstu.your_surname`. 

В случае работы с Maven общепринятым считается использовать `groupId` проекта в качестве префикса всех пакетов.

**Comment by angdust** [comment]
Исправил название "компании", изменил префиксы пакетов.

**Comment by JohnKhandygo** [comment]
У Вас `groupId` сейчас равен `org.spbstu.nikitin` и это очень хорошо. В то же время, пакет в проекте называется `bitset`. Либо Вы не понимаете, что значит "префикс", либо одно из двух.

**Comment by angdust** [comment]
Почитал и добавил префикс для пакета (но не org.spbstu.niktin, а только nikitin, потому что слишком длинный получается тогда)

**Comment by JohnKhandygo** [comment]
Не понял аргумента про очень длинное название пакета. Но окей. Главное, чтобы Вы суть уловили.
