### ISSUE TITLE
Task 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [angdust/BitSet#9]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**transpose**
“Транспонирует” входной текст по входящим в него словам, разделённым последовательностями пробелов, т.е. если входящий файл содержал строки “A    B C” и “D E”, то результатом будет файл со строками “A D”, “B E” и “C”.

file задаёт имя входного файла. Если параметр отсутствует, следует считывать текст с консоли.
Флаг -o ofile  задаёт имя выходного файла. Если параметр отсутствует, следует выводить результаты на консоль.
Флаг -a num означает, что в выходном тексте каждое слово должно занимать num символов, а оставшееся место (если оно есть) должно быть заполнено пробелами.
Флаг -t означает, что если слово “не влезает” в выделенное для него место (флагом -а), то его следует обрезать до нужного размера.
Флаг -r означает, что слово в рамках выделенного для него места (флагом -а) следует выравнивать по правой границе. Если данный флаг не указан, слово выравнивается по левой границе.

Command line: transpose [-a num] [-t] [-r] [-o ofile] [file]

В случае, когда какое-нибудь из имён файлов указано неверно, следует выдать ошибку. В случае, если флаг -а отсутствует, но присутствуют флаги -t или -r, следует выравнивать текст так, будто указан флаг “-а 10”.

Кроме самой программы, следует написать автоматические тесты к ней.

Также необходимо разработать скрипты и/или инструкции сборки и запуска разработанного приложения из командной строки. 

**P.S.** Проверка второго задания начинается не раньше исправления всех замечания к первому заданию. В любом случае напишите в комментариях к этому issue, когда задание будет готово к проверке.

**P.S.S.** Если будете делать это задание в другом репозитории, дайте ссылку в комментариях к этому issue.

**Comment by angdust** [comment]
Можно получить пояснение. При использовании флага -a num, если слово короткое, то добавляются пробелы, а если слово "не влезает", то оно не обрезается, так как есть флаг -t?

**Comment by JohnKhandygo** [comment]
Да. То есть слова обрезаются под `num` только если есть флаг `-t`. В противном случае оно либо дополняется пробелами, либо остается как есть.

**Comment by angdust** [comment]
Сделал черновик второго задания.
Ссылка на репозиторий https://github.com/angdust/transpose

**Comment by JohnKhandygo** [comment]
Для удобства переношу условие задания в новый репозиторий, все замечания будут появляться уже там.
